version: "3.8"

services:
#  db:
#    image: postgres
#    environment:
#      POSTGRES_PASSWORD: password

  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
#    environment:
#      DATABASE_NAME: postgres
#      DATABASE_USER: postgres
#      DATABASE_PASSWORD: password
#      DATABASE_HOST: db
#      DATABASE_PORT: "5432"
    volumes:
      - './app:/app/app:z'
    ports:
      - 8000:8000
#    depends_on:
#      - db

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./start-celeryworker.sh
    environment:
      - FLASK_APP=app
      - CELERY_BROKER_HOST=host.docker.internal
      - CELERY_BROKER_PORT=17110


  celery_beat:
      build:
        context: .
        dockerfile: Dockerfile
      command: ./start-celerybeat.sh
      env_file:
        - .env
      environment:
        - FLASK_APP=app

#  flower:
#      build:
#        context: .
#        dockerfile: Dockerfile
#      command: ./start-flower.sh
#      env_file:
#        - .env
#      environment:
#        - FLASK_APP=app
#      ports:
#        - 8001:8000

