version: "3.8"

services:
  app:
    image: app
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - './app:/app/app:z'
    command:
      - "python"
      - "-m"
      - "app"
      - "--reload"
    ports:
      - 8000:8000

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    image: flask_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_APP=app


  celery_beat:
      build:
        context: .
        dockerfile: ./compose/local/flask/Dockerfile
      image: flask_celery_beat
      command: /start-celerybeat
      volumes:
        - .:/app
      env_file:
        - .env
      environment:
        - FLASK_APP=app


  flower:
      build:
        context: .
        dockerfile: ./compose/local/flask/Dockerfile
      image: flask_celery_flower
      command: /start-flower
      volumes:
        - .:/app
      env_file:
        - .env
      environment:
        - FLASK_APP=app
      ports:
        - 8000:8000

