name: CICD
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  #####################################################
  # Run tests and (not yet implemented publish coverage
  #####################################################
  test:
    runs-on: oci-shared
    # uses: projectronin/github/.github/workflows/python_test.yml
    # secrets:
    #   (none at this time)
    steps:
      - name: test
        run: echo "I solemnly swear I am up to no good and have no tests."
  application-image:
    runs-on: oci-shared
    if: github.ref == 'refs/heads/main'
    needs:
      - test
    steps:
      - id: get-version
        uses: projectronin/github/get-version@get-version/v3

      - name: Push multiplatform application image to Nexus
        uses: projectronin/github/.github/workflows/image_push_nexus.yml@image_push_nexus/v4
        with:
          image-tag: ${{ steps.get-version.outputs.version }}
          repo: "infx-internal-tools"
          username: ${{ secrets.NEXUS_DOCKER_USERNAME }}
          password: ${{ secrets.NEXUS_DOCKER_PASSWORD }}

      - id: set-version
        uses: projectronin/github/set-version@set-version/v2
        with:
          semver: "${{ steps.get-version.outputs.version }}"

  deploy_dev:
    if: github.ref == 'refs/heads/main' || contains(github.ref, 'hotfix/')
    uses: projectronin/ronin-charts/.github/workflows/deploy.yaml@deploy/v3
    needs: [application-image]
    with:
      environment: dev
      application: infx-internal-tools
      tag: ${{ github.sha }}
      commit-sha: ${{ github.sha }}
    secrets: inherit

  deploy_stage:
    if: github.ref == 'refs/heads/main' || contains(github.ref, 'hotfix/')
    uses: projectronin/ronin-charts/.github/workflows/deploy.yaml@deploy/v3
    needs: [deploy_dev]
    with:
      environment: stage
      application: infx-internal-tools
      tag: ${{ github.sha }}
      commit-sha: ${{ github.sha }}
    secrets: inherit

  deploy_prod:
    if: github.ref == 'refs/heads/main' || contains(github.ref, 'hotfix/')
    uses: projectronin/ronin-charts/.github/workflows/deploy.yaml@deploy/v3
    needs: [deploy_stage]
    with:
      environment: prod
      application: infx-internal-tools
      tag: ${{ github.sha }}
      commit-sha: ${{ github.sha }}
    secrets: inherit